app/Http/routes.php
<?php
// use Realestate/Traits/Admin;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|colo
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// $menu->sessions($data/userdate) / MENU::input($menudata = [])->sessions(data)
			// ->filterby([index]=> asc, desc,[except]=>['dashboard'] = null)
			// ->domain([view=>all, self, specific] = null)
			// ->securityLevel(['highest#'=>'1',lowest=>'8']= null)
			// ->get([all,visible,hidden, ] = null);

// menu = $routes->middleware('checker')

// $r = new  Sulsira\Accounts\Rent;
//dd($r->payment([
//    'payment' => 400,
//    'month_fee' => 100,
//    'balance'=> 300,
//    'last_paid_date' => '2015-1-31',
//    'current_payment_date' => date("Y-m-d", time()),
//    'previouly_assigned_payment_date'=> '2015-4-30'
//
//]));
//;
//
//dd( Accounts::mortgage()->pay([
//       'amount_paid' => 500 + 50+0,
//       'total_paid' => 0,
//       'payment_due'=> 0,
//       'payment_duration_in_months'=> 30,
//       'calculated_monthly_fee' => 0,
//       'number_of_months_paid' => 0,
//       'unhindered_closing_payment_date'=> null,
//       'next_payment_date' => null,
//       'commencement_date' => '2015-7-26',
//       'payment_type' => null,
//       'down_payment' => 5000,
//       'plot_price' => 75000,
//       'paid_date' => date("Y-m-d", time()),
//       'arrears' => null,
//       'balance' => null
//   ])->getPayment()
//);

//$account = new Sulsira\Accounts\Account::rent();
//var_dump($account->rent());
//// ACCOUNTS
//
//        ->RENT/MORTGATE/LOTSALE/BANCK/EXPENSES/CHARGES/SALARY/()
//          ->PAY/GET/DELETE/()
//        ->getTrasactions/get/getStatus/
//dd(
//   Sulsira\Accounts\Mortgage::pay()->getPayment()
//);

//use Illuminate\Support\Facades\Session;use Sulsira\Menu\Menu;

//$user_id = session('user_id');
//$security_level = session('security_level');
//$domain = session('domain');
//$usergroup = session('usergroup');
//$url  = session('url');
//$department = session('department');
//
//$arg = compact('user_id','security_level', 'domain','usergroup','url','department');
//var_dump($arg);
//var_dump(Sulsira\Menu\Menu::topbar());
// date('birthday', unix, );

Route::get('/','WelcomeController@index');

Route::get('logout', 'Auth\AuthController@getLogout');
Route::get('home', 'HomeController@index');
Route::get('rejected', 'PublicController@getRejected');
Route::post('login', 'Auth\AuthController@postLogin');
Route::controllers([
	'password' => 'Auth\PasswordController'
]);

// admin based routes
Route::resource('admin/dashboard', 'AdminController@getDashboard');
Route::resource('admin', 'AdminController');
Route::resource('users', 'UsersController');

// estate based routes
Route::get('estate/dashboard', 'EstateController@getDashboard');
Route::resource('estate', 'EstateController');
Route::resource('estates', 'EstatesController');

Route::group(['prefix'=>'plots'], function(){
//    Route::get('plots/customers', 'PlotsCustomersController@index');
    Route::resource('customers', 'PlotsCustomersController');
});
Route::resource('plots', 'plotsController');

// accounts based routes
Route::group(['prefix'=>'accounts'], function(){

    Route::resource('dashboard', 'AccountsController@getDashboard');

    //account customers base routes
    Route::resource('customers', 'CustomersController');
    Route::resource('transactions', 'TransactionsController');
    Route::resource('invoices', 'InvoicesController');
    Route::resource('receipts', 'ReceiptsController');
    Route::resource('incomes','IncomesController');
    Route::resource('expenses','ExpensesController');

    Route::resource('/', 'AccountsController');
});
//
//DB::listen(function($q, $b, $t){
//   var_dump($q);
//});

resources/views/templates/account.blade.php
@extends('layouts.dashboard')
@section('styles')
    @parent
 	{!! HTML::style('css/scheme.css') !!}
@stop
@section('header')
    @include('_partials/header')
@stop
@section('sidebar')
    <div class="col-sm-3 col-md-2 sidebar">
        @include('_partials/sidebar')

		  <ul class="nav nav-sidebar" id="snav">
		    <li>
		        <a href="#">
		            <span class="octicon octicon-organization"></span>
		            <span>Statements</span>
		        </a>
		    </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-location"></span>
		            <span>Revenue</span>
		        </a>
		      </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-diff-ignored"></span>
		            <span>Income</span>
		        </a>
		      </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-unfold"></span>
		            <span> Expense</span>

		        </a>
		      </li>
		  </ul>
		  @if(isset($header))
            @if( array_get($header, 'system') )
		        <ul class="nav nav-sidebar" id="systems">
		  		    <li>
		  		        <a href="">
		  		        	<span class="octicon octicon-versions"></span> <span>Systems</span>
          		    	</a>
          		    </li>
                    @foreach( array_get( $header, 'system' ) as $sys => $system)
                                <li class="system">
                                    <a href="">
                                        <span class="octicon octicon-diff-ignored"></span>
                                        <span>{{ucwords($sys)}}</span>
                                    </a>
                                  @if(isset($system) and !empty($system))
                                     <ul class="nav nav-sidebar system-menu">
                                        @foreach($system as $menu)
                                           @if((int)$menu['visible'])
                                                <li>
                                                    <a href="">
                                                        <span class="octicon octicon-unfold"></span>
                                                        <span> {{ucwords($menu['name'])}}</span>

                                                    </a>
                                                </li>
                                           @endif
                                        @endforeach
                                     </ul>

                                  @endif
                                </li>
                    @endforeach
		        </ul>
            @endif
		  @endif
		  <ul class="nav nav-sidebar">
		    <li><a href=""><span class="octicon octicon-versions"></span> <span>
		        Menu view</span></a></li>
		  </ul>
    </div>
@stop
@section('container')

	<div class="main_content col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
	    @include('_partials/fetch')
	    @if(str_contains($user_details['previledges'], 'a'))
           <nav class="add-nav breadcrumbs">
                <ol class="breadcrumb">
                <li <?php echo ($target == 'accounts/transactions/create')? ' class="active" ': '';?>>
                      <a href="{{route('accounts.transactions.create')}}">
                        <i class="octicon octicon-plus"></i>
                         Transaction
                      </a>
                  </li>
                  <li <?php echo ($target == 'accounts/customers/create')? ' class="active" ': '';?>>
                      <a href="{{route('accounts.customers.create')}}">
                        <i class="octicon octicon-plus"></i>
                         Customer
                      </a>
                  </li>
                  <li <?php echo ($target == 'accounts/invoices/create')? ' class="active" ': '';?>>
                      <a href="{{route('accounts.invoices.create')}}" class="-adder">
                            <i class="octicon octicon-plus"></i>
                            Invoice
                       </a>
                  </li>
                  <li <?php echo ($target == 'accounts/receipts/create')? ' class="active" ': '';?>>
                      <a href="{{url('accounts/receipts/create')}}" class="-adder">
                          <i class="octicon octicon-plus"></i>
                           Receipt
                      </a>
                  </li>
                  <li <?php echo ($target == 'accounts/incomes/create')? ' class="active" ': '';?>>
                      <a href="{{url('accounts/incomes/create')}}" class="-adder">
                          <i class="octicon octicon-plus"></i>
                           Income
                      </a>
                  </li>
                  <li <?php echo ($target == 'accounts/expenses/create')? ' class="active" ': '';?>>
                      <a href="{{url('accounts/expenses/create')}}" class="-adder">
                          <i class="octicon octicon-plus"></i>
                           Expense
                      </a>
                  </li>

                </ol>
            </nav>
        @endif
	    @include('_partials/loader')
	    <div class="main cc">
@stop

resources/views/templates/account_end.blade.php
    </div> <!-- main cc -->
</div> <!-- main_conent-->
@section('footer')

 	@include('inc/footer')
@show

resources/views/templates/admin.blade.php
@extends('layouts.dashboard')
@section('styles')
    @parent
 	{!! HTML::style('css/scheme.css') !!}
@stop
@section('header')
    @include('_partials/header')
@stop
@section('sidebar')
       <div class="col-sm-3 col-md-2 sidebar">
           @include('_partials/sidebar')



		  <ul class="nav nav-sidebar" id="snav">
		    <li>

		        <a href="#">
		            <span class="octicon octicon-organization"></span>
		            <span>customers</span>
		        </a>
		    </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-location"></span>
		            <span>plots</span>
		        </a>
		      </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-diff-ignored"></span>
		            <span>compounds</span>
		        </a>
		      </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-unfold"></span>
		            <span> transactions</span>

		        </a>
		      </li>
		  </ul>
		  @if(isset($header))
            @if( array_get($header, 'system') )
		        <ul class="nav nav-sidebar" id="systems">
		  		    <li>
		  		        <a href="">
		  		        	<span class="octicon octicon-versions"></span> <span>Systems</span>
          		    	</a>
          		    </li>
                    @foreach( array_get( $header, 'system' ) as $sys => $system)
                                <li class="system">
                                    <a href="">
                                        <span class="octicon octicon-diff-ignored"></span>
                                        <span>{{ucwords($sys)}}</span>
                                    </a>
                                  @if(isset($system) and !empty($system))
                                     <ul class="nav nav-sidebar system-menu">
                                        @foreach(array_get($system, 'pages') as $menu)

                                           @if((int)$menu['visible'])
                                                <li>
                                                    <a href="">
                                                        <span class="octicon octicon-unfold"></span>
                                                        <span> {{ucwords($menu['name'])}}</span>

                                                    </a>
                                                </li>
                                           @endif
                                        @endforeach
                                     </ul>

                                  @endif
                                </li>
                    @endforeach
		        </ul>
            @endif
		  @endif
		  <ul class="nav nav-sidebar">
		    <li><a href=""><span class="octicon octicon-versions"></span> <span>
		        Menu view</span></a></li>
		  </ul>


       </div>
@stop
@section('container')
	<div class="main_content col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
	    @include('_partials/fetch')
	    @include('_partials/breadcrumb')
	    @include('_partials/loader')
	    <div class="main cc">
@stop

resources/views/templates/admin_end.blade.php
    </div> <!-- main cc -->
</div> <!-- main_conent--> 
@section('footer')
 
 	@include('inc/footer')
@show

resources/views/templates/dashboard.blade.php
@extends('layouts.dashboard')
@section('styles')
    @parent
 	{!! HTML::style('css/scheme.css') !!}
@stop
@section('header')
	<header>
	    <nav class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container-fluid">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	            <div class="navbar-brand" id="comenu">
	           <a href="#" id="company_logo">
	             <span>Company properties</span>
	            </a>
	            <a href="#" id="triger"><span class="octicon octicon-three-bars"></span></a>                   
	            </div>
	        </div>
	        <div id="navbar" class="navbar-collapse collapse">
	            <ul class="nav navbar-nav">
	                        <li class="active"><a href="#">Home</a></li>
	                        <li><a href="#about">About</a></li>
	                        <li><a href="#contact">Contact</a></li>
	                      </ul>
	            <ul class="nav navbar-nav  navbar-right" id="userdrop">
	                <li class="dropdown">
	                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">

	                      <img src="img/login_bg.jpg" title="user impage" class="img-circle"> Dropdown <span class="caret"></span>   

	                    
	                    </a>
	                  <ul class="dropdown-menu" role="menu">
	                    <li><a href="#">Action</a></li>
	                    <li><a href="#">Another action</a></li>
	                    <li><a href="#">Something else here</a></li>
	                    <li class="divider"></li>
	                    <li class="dropdown-header">Nav header</li>
	                    <li><a href="#">Separated link</a></li>
	                    <li><a href="#">One more separated link</a></li>
	                  </ul>
	                </li>
	             </ul>
	        </div>
	      </div>
	    </nav>
	</header>
@stop
@section('sidebar')
	<div class="col-sm-3 col-md-2 sidebar">
		  <ul class="nav nav-sidebar userbrief" >
		      <li class="department">
		          <strong>
		              Department <span class="sr-only">(current)</span>
		          </strong>                                        
		      </li>
		      <li>
		          <strong>
		              admin
		          </strong>                   
		      </li>
		      <li class="thumber">
		              <img src="img/login_bg.jpg" alt="user name here" class="img-circle">
		      </li>
		      <li>
		          User fullname
		      </li>
		      <li class="cons">
		          <a href="#">
		              <span class="octicon octicon-broadcast"></span>
		          </a>
		          <a href="#">
		              <span class="octicon octicon-gear"></span>
		          </a>
		      </li>
		  </ul>
		  <ul class="nav nav-sidebar" id="snav">
		    <li>
		        <a href="#">
		            <span class="octicon octicon-organization"></span>
		            <span>customers</span>
		        </a>
		    </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-location"></span>
		            <span>plots</span>
		        </a>
		      </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-diff-ignored"></span>
		            <span>compounds</span>                             
		        </a>
		      </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-unfold"></span>
		            <span> transactions</span>

		        </a>
		      </li>
		  </ul>
		  <ul class="nav nav-sidebar">
		    <li><a href=""><span class="octicon octicon-versions"></span> <span>
		        Menu view</span></a></li>
		  </ul>
	  </div>  
@stop
@section('container')
	<div class="main_content col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
	    @include('_partials/fetch')
	    @include('_partials/breadcrumb')
	    @include('_partials/loader')
	    <div class="main cc">
@stop

resources/views/templates/dashboard_end.blade.php
    </div> <!-- main cc -->
</div> <!-- main_conent--> 
@section('footer')
 
 	@include('inc/footer')
@show

resources/views/templates/dashboards.blade.php
@extends('layouts.dashboard')
@section('styles')
    @parent
 	{!! HTML::style('css/scheme.css') !!}
@stop
@section('header')
    @include('_partials/header')
@stop
@section('sidebar')
    @include('_partials/sidebar')
@stop
@section('container')
	<div class="main_content col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
	    @include('_partials/fetch')
	    @include('_partials/breadcrumb')
	    @include('_partials/loader')
	    <div class="main cc">
@stop

resources/views/templates/dashboards_end.blade.php
    </div> <!-- main cc -->
</div> <!-- main_conent-->
@section('footer')

 	@include('inc/footer')
@show

resources/views/templates/estate.blade.php
@extends('layouts.dashboard')
@section('styles')
    @parent
 	{!! HTML::style('css/scheme.css') !!}
@stop
@section('header')
    @include('_partials/header')
@stop
@section('sidebar')
    <div class="col-sm-3 col-md-2 sidebar">
        @include('_partials/sidebar')

		  <ul class="nav nav-sidebar" id="snav">
		    <li>
		        <a href="#">
		            <span class="octicon octicon-organization"></span>
		            <span>customers</span>
		        </a>
		    </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-location"></span>
		            <span>plots</span>
		        </a>
		      </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-diff-ignored"></span>
		            <span>compounds</span>
		        </a>
		      </li>
		    <li>
		        <a href="">
		            <span class="octicon octicon-unfold"></span>
		            <span> transactions</span>

		        </a>
		      </li>
		  </ul>
		  @if(isset($header))
            @if( array_get($header, 'system') )
		        <ul class="nav nav-sidebar" id="systems">
		  		    <li>
		  		        <a href="">
		  		        	<span class="octicon octicon-versions"></span> <span>Systems</span>
          		    	</a>
          		    </li>
                    @foreach( array_get( $header, 'system' ) as $sys => $system)
                                <li class="system">
                                    <a href="">
                                        <span class="octicon octicon-diff-ignored"></span>
                                        <span>{{ucwords($sys)}}</span>
                                    </a>
                                  @if(isset($system) and !empty($system))
                                     <ul class="nav nav-sidebar system-menu">
                                        @foreach($system as $menu)
                                           @if((int)$menu['visible'])
                                                <li>
                                                    <a href="">
                                                        <span class="octicon octicon-unfold"></span>
                                                        <span> {{ucwords($menu['name'])}}</span>

                                                    </a>
                                                </li>
                                           @endif
                                        @endforeach
                                     </ul>

                                  @endif
                                </li>
                    @endforeach
		        </ul>
            @endif
		  @endif
		  <ul class="nav nav-sidebar">
		    <li><a href=""><span class="octicon octicon-versions"></span> <span>
		        Menu view</span></a></li>
		  </ul>
    </div>
@stop
@section('container')
	<div class="main_content col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
	    @include('_partials/fetch')
	    @if(str_contains($user_details['previledges'], 'a'))
           <nav class="add-nav breadcrumbs">
                <ol class="breadcrumb">
                  <li <?php echo ($target == 'estates/create')? ' class="active" ': '';?>>
                      <a href="{{route('estates.create')}}" class="adder" data-toggle="modal" data-target="#estate_add" data-whatever="@mdo">
                        <i class="octicon octicon-plus"></i>
                         Estates
                      </a>
                  </li>
                  <li <?php echo ($target == 'plots/create')? ' class="active" ': '';?>>
                      <a href="{{route('plots.create')}}" class="-adder">
                            <i class="octicon octicon-plus"></i>
                            Plots
                       </a>
                  </li>
                  <li <?php echo ($target == 'plots/customers/create')? ' class="active" ': '';?>>
                      <a href="{{url('plots/customers/create')}}" class="-adder">
                          <i class="octicon octicon-plus"></i>
                           Customers
                      </a>
                  </li>

                </ol>
            </nav>
        @endif
	    @include('_partials/loader')
	    <div class="main cc">
@stop

resources/views/templates/estate_end.blade.php
    </div> <!-- main cc -->
</div> <!-- main_conent-->
@section('footer')

 	@include('inc/footer')
@show

resources/views/templates/login.blade.php
@extends('layouts.login')
@section('styles')
    @parent
        <link rel="stylesheet" type="text/css" href="{{('css/sticky.css')}}">
        <link rel="stylesheet" type="text/css" href="{{('css/login.css')}}">
@stop

@section('header')
	<header>
		<h1>real properties</h1>
      <h4>property management system v0.7 </h4><span>(PMS V0.7)</span>
      <hr>
	</header>
@stop

@section('content')

resources/views/templates/login_end.blade.php
@stop
@section('footer')
 	@include('inc/footer')
@show

resources/views/templates/public.blade.php
{{-- this the zone that takes sections for certain views --}}